// Plain-language explainer scripts. Template-based - written by hand, no AI, not medical advice.
window.PROCS = {
 filling:{icon:'🔧',name:{en:'Filling',es:'Empaste'},time:'30–60 min',steps:[
  {anim:'decay', en:['A small cavity is a soft spot where bacteria wore through the hard outer layer.','This tooth has a little hole. Germs made it.'], es:['Una caries pequeña es una zona blanda donde las bacterias dañaron la capa exterior.','Este diente tiene un hoyito. Lo hicieron los gérmenes.']},
  {anim:'numb', en:['The area is numbed first, so you feel pressure but not pain.','We make the tooth sleepy so it does not hurt.'], es:['Primero se adormece la zona: sentirás presión pero no dolor.','Dormimos el diente para que no duela.']},
  {anim:'drill', en:['The soft, damaged part is gently cleaned out.','We clean out the germs.'], es:['Se limpia suavemente la parte dañada.','Limpiamos los gérmenes.']},
  {anim:'fill', en:['Tooth-colored material fills the space and is hardened with a blue light.','We fill the hole and a blue light makes it hard.'], es:['Un material del color del diente rellena el espacio y se endurece con luz azul.','Llenamos el hoyito y una luz azul lo endurece.']},
  {anim:'done', en:['The bite is checked and polished. You can usually eat once the numbness wears off.','All done! Wait until your mouth wakes up to eat.'], es:['Se revisa la mordida y se pule. Normalmente puedes comer cuando pase el adormecimiento.','¡Listo! Espera a que tu boca despierte para comer.']}],
  care:{en:['Avoid chewing on the numb side for a few hours','Mild sensitivity for a few days is common','Call the office if your bite feels high'],es:['Evita masticar del lado adormecido por unas horas','Es común algo de sensibilidad unos días','Llama si sientes la mordida alta']}},
 crown:{icon:'👑',name:{en:'Crown',es:'Corona'},time:'2 visits, or 1 with same-day milling',steps:[
  {anim:'crack', en:['A crown is a cap for a tooth that is cracked, weak, or heavily filled.','This tooth is tired and cracked. It needs a helmet.'], es:['Una corona es una funda para un diente agrietado, débil o con muchos empastes.','Este diente está cansado. Necesita un casco.']},
  {anim:'numb', en:['The tooth is numbed.','We make the tooth sleepy.'], es:['Se adormece el diente.','Dormimos el diente.']},
  {anim:'shape', en:['The tooth is shaped down a little so the cap fits over it.','We make the tooth a bit smaller so the helmet fits.'], es:['Se reduce un poco el diente para que la funda encaje.','Hacemos el diente más pequeño para que quepa el casco.']},
  {anim:'scan', en:['A scan or impression records the exact shape for the lab or mill.','We take a picture of the tooth shape.'], es:['Un escaneo o impresión registra la forma exacta.','Tomamos una foto de la forma del diente.']},
  {anim:'crown', en:['The crown is bonded on, covering and protecting the whole tooth.','The helmet goes on. Strong tooth!'], es:['La corona se cementa, cubriendo y protegiendo todo el diente.','¡Se pone el casco! ¡Diente fuerte!']}],
  care:{en:['With a temporary crown, avoid sticky foods','Brush and floss around it like a normal tooth','Call if the crown feels loose'],es:['Con corona temporal, evita alimentos pegajosos','Cepilla y usa hilo dental normalmente','Llama si la corona se siente floja']}},
 rootcanal:{icon:'🌱',name:{en:'Root canal',es:'Endodoncia'},time:'60–90 min',steps:[
  {anim:'infect', en:['Inside every tooth is soft pulp. When it gets infected, it can hurt and swell.','The inside of the tooth is sick.'], es:['Dentro de cada diente hay pulpa. Si se infecta puede doler e inflamarse.','El interior del diente está enfermo.']},
  {anim:'numb', en:['The tooth is fully numbed. Most people say it feels like a long filling.','We make the tooth sleepy.'], es:['Se adormece por completo. Muchos dicen que se siente como un empaste largo.','Dormimos el diente.']},
  {anim:'drill', en:['A small opening lets the infected pulp be removed and the canals cleaned.','We clean the sick part inside.'], es:['Una pequeña abertura permite retirar la pulpa infectada y limpiar los conductos.','Limpiamos la parte enferma de adentro.']},
  {anim:'canals', en:['The canals are filled and sealed so bacteria cannot get back in.','We seal it up tight.'], es:['Los conductos se rellenan y sellan para que no entren bacterias.','Lo sellamos bien.']},
  {anim:'crown', en:['A crown is often placed afterward to protect the tooth.','Often the tooth gets a helmet after.'], es:['A menudo se coloca una corona después para protegerlo.','Muchas veces el diente recibe un casco después.']}],
  care:{en:['Tenderness for a few days is normal','Avoid hard food on that side until the final crown','Take medication only as your dentist directs'],es:['Es normal algo de sensibilidad unos días','Evita alimentos duros de ese lado hasta la corona final','Toma medicamentos solo como indique tu dentista']}},
 implant:{icon:'🔩',name:{en:'Implant',es:'Implante'},time:'several visits over months',steps:[
  {anim:'missing', en:['An implant replaces a missing tooth from the root up.','A tooth is missing. We can build a new one.'], es:['Un implante reemplaza un diente perdido desde la raíz.','Falta un diente. Podemos hacer uno nuevo.']},
  {anim:'post', en:['A small titanium post is placed in the jaw, acting as a new root.','A little post goes in like a new root.'], es:['Se coloca un pequeño poste de titanio en el hueso, como nueva raíz.','Un postecito entra como raíz nueva.']},
  {anim:'heal', en:['Over a few months, bone grows around the post and locks it in.','The bone hugs the post while it heals.'], es:['En unos meses, el hueso crece alrededor del poste y lo fija.','El hueso abraza el poste mientras sana.']},
  {anim:'abut', en:['A connector piece is attached on top.','A connector goes on top.'], es:['Se coloca una pieza de conexión arriba.','Se pone un conector arriba.']},
  {anim:'crown', en:['A custom crown completes the tooth.','The new tooth goes on top!'], es:['Una corona a medida completa el diente.','¡El diente nuevo va arriba!']}],
  care:{en:['Follow the post-surgery instructions closely','Soft foods for the first days','Clean around it daily, just like natural teeth'],es:['Sigue las instrucciones postoperatorias','Comida blanda los primeros días','Limpia alrededor a diario como un diente natural']}},
 cleaning:{icon:'✨',name:{en:'Cleaning',es:'Limpieza'},time:'30–60 min',steps:[
  {anim:'tartar', en:['Plaque that is not brushed away hardens into tartar, which a brush cannot remove.','Old plaque gets hard like rock.'], es:['La placa que no se cepilla se endurece en sarro, que el cepillo no quita.','La placa vieja se pone dura como piedra.']},
  {anim:'scale', en:['Tartar is gently scraped or vibrated off above and just below the gumline.','We gently scrape it off.'], es:['El sarro se retira suavemente por encima y debajo de la encía.','Lo quitamos con cuidado.']},
  {anim:'polish', en:['The teeth are polished smooth, which makes it harder for plaque to stick.','We polish the teeth shiny.'], es:['Se pulen los dientes para que la placa no se pegue fácilmente.','Pulimos los dientes brillantes.']},
  {anim:'done', en:['Floss and a check of gum health finish the visit.','Shiny and clean!'], es:['Hilo dental y revisión de encías terminan la visita.','¡Brillante y limpio!']}],
  care:{en:['Brush 2 minutes, twice a day','Floss once a day','Book your next visit as recommended'],es:['Cepilla 2 minutos, dos veces al día','Usa hilo dental una vez al día','Agenda tu próxima visita']}},
 sealant:{icon:'🛡️',name:{en:'Sealants',es:'Selladores'},time:'about 5 min per tooth',steps:[
  {anim:'grooves', en:['Back teeth have deep grooves where food and bacteria hide.','Back teeth have little hiding spots for germs.'], es:['Las muelas tienen surcos profundos donde se esconden bacterias.','Las muelas tienen escondites para gérmenes.']},
  {anim:'polish', en:['The tooth is cleaned and dried. No drilling and no numbing needed.','We clean the tooth. No shots!'], es:['Se limpia y seca el diente. Sin taladro ni anestesia.','Limpiamos el diente. ¡Sin inyección!']},
  {anim:'fill', en:['A thin coating is painted into the grooves and hardened with light.','We paint a raincoat on the tooth.'], es:['Se pinta una capa fina en los surcos y se endurece con luz.','Pintamos un impermeable en el diente.']},
  {anim:'done', en:['The sealed grooves are much harder for cavities to start in.','Now germs cannot hide!'], es:['Los surcos sellados resisten mucho más las caries.','¡Ahora los gérmenes no pueden esconderse!']}],
  care:{en:['Eat normally right away','Sealants are checked at regular visits','Keep brushing - sealants help, they do not replace brushing'],es:['Puedes comer normalmente','Se revisan en las visitas regulares','Sigue cepillando: ayudan pero no reemplazan el cepillado']}},
};
